### ISSUE TITLE
Update README.... Source of the data?

### ISSUE THREAD

**Issue by germolinal** [teddythepooh/hedonic_price_modeling#1]
Hello, 

I am wondering where did you get this data, and whether I can use it for publications 

Thanks!

**Comment by teddythepooh** [comment]
Yes, of course. I was just using the data to practice my programming
skills. Please refer to the two links below for the documentation:


http://jse.amstat.org/v19n3/decock.pdf

https://cran.r-project.org/web/packages/AmesHousing/AmesHousing.pdf

**Comment by germolinal** [comment]
Excellent! Thanks very much! In the publications, should I just reference the decock article?
